version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: CosmosOdyssey-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cosmos
      - POSTGRES_PASSWORD=odyssey
      - POSTGRES_DB=cosmos_odyssey
    networks:
      - cosmos_net

  pgadmin4:
    image: dpage/pgadmin4:8
    container_name: pgadmin-CosmosOdyssey
    ports:
      - 8080:80
    volumes:
      - cosmos-pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - cosmos_net
  
  backend:
    image: cosmos-odyssey-backend
    container_name: cosmos-odyssey-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://cosmos:odyssey@postgres:5432/cosmos_odyssey
    depends_on:
      - postgres
    networks:
      - cosmos_net

networks:
  cosmos_net:

volumes:
  cosmos-pgadmin-data: